### ISSUE TITLE
Reset Flags Doesn't Reset Dampe's Initial Tour Text

### ISSUE THREAD

**Issue by Ecksters** [glankk/gz#10]
When beginning Dampe's Heart-Pounding Grave-Digging Tour, using Reset Flags in the graveyard doesn't reset the text for him explaining the minigame initially. 

Not sure if you're interested in adding the non-flag "flags" to the Reset Flags option or not.

**Comment by glankk** [comment]
The `clear flags` and `set flags` in the scene menu is specifically for flags related to the scene. The flag you described is not stored in the scene flags, so this is not an error. Resetting this flag can be done using memory files, or with the upcoming flag editor.
