### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by g-mips** [glankk/gz#13]
So this is an issue, but I also have a question.

Issue first:
--------------------------------
I'm on Windows 10 using the Ubuntu subsystem. I went through the steps of configuring, building, and installing the n64 repo. I ran `make` for gz as well.

I'm sure that there was something that I did wrong but when I try running `./patch-wad <wad>`, I get this error
`making patched wad from `Zelda no Densetsu - Toki no Okarina.wad`...lua/patch-wad.lua:33: libgru error 4: file input error`

It looks like that lua file on that line is looking for a file in the `ups` directory, but it is empty for me. Now if I run `patch/make-wad <wad>` it seems to be successful. It creates `gz-oot-vc-j.wad` with a bigger size than the original wad. So that seemed to work. Am I missing a step to run `patch-wad`?

Question:
-------------------------------
The questions relates to this issue. What is the difference between running `make-wad` and `patch-wad`? Which do I want to run if I want to get the "practice wad" as a channel on the wii?

Sorry if this was answered in the documentation, I couldn't seem to find an answer to it. I think the issue is I don't understand what a UPS patch is.

Thanks for your patience, work, and help!

**Comment by g-mips** [comment]
This was a misunderstanding on my end of how `patch-wad` works. Needed to create the ups file first through running `make-patch-vc` and then `patch-wad`.

**Comment by samwho** [comment]
I also bumped in to this problem when I first tried to patch a ROM. It's not clear that make-patch has to be run first. Perhaps a documentation change is needed here?

**Comment by glankk** [comment]
Agreed, the purpose of each script in `/patch` should be described in BUILDING.
