### ISSUE TITLE
Suggestion: Port to Master Quest

### ISSUE THREAD

**Issue by DerpyBubblez** [glankk/gz#14]

**Comment by kdjmonaghan** [comment]
Spookily enough, minutes before you opened this issue I said to Glankk I'll look into the memory addresses for MQ.

Considered and discussing with Glankk.

**Comment by zarunet** [comment]
Any news on this? I would like to start speedrunning on MQ, and having the practice rom for it would be a godsend

**Comment by krimtonz** [comment]
I started working on it. But haven’t finished.

**Comment by aplumafreak500** [comment]
afaik the memory addresses for MQ and the normal GC ROM are the same (in fact, the `code` file is the exact same save for the buildstring). So having MQ support would also mean having support for the normal GC ROM, so this would be like hitting two Guays with one arrow.

**Comment by krimtonz** [comment]
I've done the addresses for MQ_J so far, but there are other things that don't work, which I need to figure out.

**Comment by Yanis42** [comment]
this issue should be closed since MQ port will come with the next release
