### ISSUE TITLE
Mac OS X issue with "readlink" and "gzinject"

### ISSUE THREAD

**Issue by gjoyner** [glankk/gz#21]
I'm having an issue creating a ROM file on Mac OS X. This is what I get (even if the .wad file is in the same folder of the `patch-wad` command):

Command: `./patch-wad ./wads/Zelda\ no\ Densetsu\ -\ Toki\ no\ Okarina.wad`
Output:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./patch-wad: line 6: gzinject: command not found
```

I've tried moving things around so (nearly) all files were in the same folder, just in case, but get the same output.

Any ideas?

**Comment by glankk** [comment]
macOS is not officially supported at the moment. As far as I know, the programs in the release package can not be run on macOS without some kind of virtualization layer, but you may be able to compile them yourself. Specifically, you would need the `gru` program from https://github.com/glankk/n64, and `gzinject` from https://github.com/krimtonz/gzinject. You would also need to replace the `patch-wad` script with the latest revision from the repo: https://github.com/glankk/gz/blob/master/patch/patch-wad.

**Comment by glankk** [comment]
macOS is supported as of 0.3.5. Closing.
