### ISSUE TITLE
Suggestion: Easy switching from watches to debug memory editor

### ISSUE THREAD

**Issue by natalyahasdied** [glankk/gz#23]
It would be nice if possible to have an easy way to switch from the two menus. For example, if hovering over a watch in the watches menu, if I want to edit it, I could press a button to have the debug memory editor auto popup with the relevant info filled in (watch address, address type). It could maybe just be some button on the same line as the watch with like, an arrow or something. Or maybe, be able to hover over the actual value the watch gives, and clicking that gives you memory editor.

Vice versa could be useful in some situations when looking at memory regions and wanting to add watches, but that type of work would normally be done in emu and I don't know a clean idea to allow for that transition.

**Comment by glankk** [comment]
This feature has been implemented in #47
