### ISSUE TITLE
Macro desync from Din's Fire cutscene

### ISSUE THREAD

**Issue by natalyahasdied** [glankk/gz#24]
Savestates fail capture Din's Fire animation camera (clockwise vs counterclockwise) correctly when replaying macros. Desyncs occur when the opposite camera occurs during playback.

When starting from same scene RNG, reloading after certain point in casting Din's changes camera

Example of macro playing correctly:
https://www.twitch.tv/zfg1/clip/ClumsyCleanLapwingBibleThump

Example of desync after reloading same macro:
https://www.twitch.tv/zfg1/clip/CleverIcySquidMrDestructoid

**Comment by glankk** [comment]
Fairy spells in general seem to be broken for savestates, zfg and seedborn have observed bugs with Farore's Wind as well.
