### ISSUE TITLE
Suggestion: Add support for patching Fig's Faster Quest

### ISSUE THREAD

**Issue by shawlucas** [glankk/gz#27]
This is my first time giving a suggestion on something, so I'm not exactly sure how to format it, but I think it would be nice to have support for patching a Faster Quest rom, with removed cutscenes and fast text. 

Don't know if anyone else is actually interested in this idea, just a suggestion though.

Thanks :)

**Comment by fig02** [comment]
Both rom hacks make use of the extra expansion pak space. Given that the practice rom is already close to running out of room with the 4mb of extra space, this doesn't seem likely.

Would be neat I agree. You could probably run the practice rom through the script that makes text fast. but integrating all the hacks that make use of asm probably won't happen. Its also out of scope of this project, so its not something that would be officially supported.

On that note, glank had an idea a while ago of adding a feature that would automatically mash text for you. I think this is something we should still look into.

**Comment by RenaKunisaki** [comment]
Maybe a "close current textbox" command?

**Comment by shawlucas** [comment]
There is currently a “quick text” cheat in the latest commits. This is an old suggestion that doesn’t really need to be addressed anymore.
