### ISSUE TITLE
Patching on Windows Subsystem for Linux (Ubuntu)

### ISSUE THREAD

**Issue by Sirius902** [glankk/gz#31]
I have installed the n64 tools as described by the building guide and I have run `make` in the `gz` directory but when I attempt to run `patch/make-rom rom.z64` I get the error message `patch/make-rom: 2: set: Illegal option -`

**Comment by glankk** [comment]
What distribution are you using for WSL, and what shell are you using?

**Comment by Sirius902** [comment]
I'm using bash on the Ubuntu WSL.

**Comment by flagrama** [comment]
Did you git clone on Windows or on Ubuntu? If you cloned on Windows you have windows newlines at the end of all the shell scripts which would cause this issue when then trying to run a shell script on Ubuntu. You likely need to clone from WSL, or disable autocrlf for this repo when you clone it on Windows somehow (I don't really find anywhere online that describes this, so I'm not sure it is possible without disabling autocrlf globally in the git config)

If you cloned on Ubuntu and it's acting up then I'm not sure what the issue would be.

**Comment by Sirius902** [comment]
@flagrama I cloned the repository from within the WSL

**Comment by Sirius902** [comment]
@flagrama I was certain that I cloned it from the WSL but as it turns out I might not have? I deleted the folder and cloned it again and that seemed to work so I guess that was the issue.

**Comment by Sirius902** [comment]
Okay, so now I can run `patch/make-rom` and it creates the correct rom but I tried to make a vc inject and installed gzinject then ran `patch/make-wad rom/oot-vc.wad` with a US OoT wad with MD5 `f30e61e4ec97d1d5736c86105ed43d91` and I get the following error message:

```
making wad from `rom/oot-vc.wad`...
unpacking wad
Extracting rom/oot-vc.wad to patch/wadextract
Creating patch/wadextract
Writing cert.cert.
Writing ticket.tik.
Writing metadata.tmd.
unpacking failed
```

**Comment by krimtonz** [comment]
The latest gzinject will not be compatible with the current gz patching scripts.

**Comment by Sirius902** [comment]
@krimtonz Ah alright. Should I just download a release version or is there a specific gzinject version I need?

**Comment by krimtonz** [comment]
I think your best bet would be to use the gzinject included with the latest gz release.

**Comment by glankk** [comment]
The latest revision I've confirmed is release 0.2.2, commit a9f402d.

**Comment by Sirius902** [comment]
Thank you for your help, I tried commit a9f402d and it worked.
