### ISSUE TITLE
BUILD issues

### ISSUE THREAD

**Issue by TheCherry** [glankk/gz#32]
Hi, I tried to compile, to use the new hitbox features.
My System is Ubuntu 19.04

I get the error that mips64-gcc is missing:
`mips64-gcc: Command not found`
But `gcc-mips64-linux-gnuabi64` and `gcc-mips-linux-gnu` are installed.

Even then I try to install the n64 toolchain, does that not work, there I get libusb undeclared errors. But libusb-1.0-0-dev is installed.

**Comment by glankk** [comment]
Could you post your `configure.log` ?

**Comment by TheCherry** [comment]
I have only a `config.log` and a `config.status` from the n64 toolchain.
[config.log](https://github.com/glankk/gz/files/3722812/config.log)
[config.status.log](https://github.com/glankk/gz/files/3722813/config.status.log)

**Comment by TheCherry** [comment]
I tried now to add all folders from /usr/lib* to the path
make clean the n64 directory
and then started again.
the toolchain was correctly build.

But then I try to compile gz, I get the same error.
My /opt/n64/bin directory have that files:
```
ed64rdb      gfxdis.f3dex   grc  luapatch          mips64-as       mips64-gdb            mips64-ld.bfd   mips64-objdump  mips64-run      mips64-strip
gfxdis.f3d   gfxdis.f3dex2  gru  mips64-addr2line  mips64-c++filt  mips64-gdb-add-index  mips64-nm       mips64-ranlib   mips64-size
gfxdis.f3db  gfxdis.f3dexb  gs   mips64-ar         mips64-elfedit  mips64-ld             mips64-objcopy  mips64-readelf  mips64-strings
```

Next I tried to edit the makefile and used as target the follow things:
`target                = mips64-linux-gnuabi64`
and
`taget                 = mips64-linux-gnu`
Now its find the binary but not the n64.h file. And I see no way to add the path from the n64.h to the makefile.
I found the n64.h in `/opt/n64/mips64/n64-sysroot/usr/include/`

**Comment by TheCherry** [comment]
Ok. Just cloned every from scratch and did as now as root.
Now Its worked.
