### ISSUE TITLE
homeboy.bin: No such file or directory

### ISSUE THREAD

**Issue by AmiableNebula** [glankk/gz#41]
Hi,

When I run `./patch/make-wad <wad>` I get:

`Extracting oot-jp.wad to patch/wadextract
Creating patch/wadextract
Writing cert.cert.
Writing ticket.tik.
Writing metadata.tmd.
Writing footer.bin
Decrypting contents 0.
Writing content0.app.
Decrypting contents 1.
Writing content1.app.
Decrypting contents 2.
Writing content2.app.
Decrypting contents 3.
Writing content3.app.
Decrypting contents 4.
Writing content4.app.
Decrypting contents 5.
Extracting content 5 uint8_t Archive.
Writing content5.app.
Decrypting contents 6.
Writing content6.app.
rom is oot-1.2-j
building gz
make: Nothing to be done for 'gz-oot-1.2-vc'.
make: Nothing to be done for 'gz-oot-1.2-vc-hooks'.
loading file system
patching code file
reassembling rom
building ldr
rm -rf obj/ldr obj/ldr/res bin/ldr
mkdir -p obj/ldr
mips64-gcc -x assembler-with-cpp -c -MMD -MP -DPACKAGE_TARNAME='gz' -DPACKAGE_URL='github.com/glankk/gz' -DF3DEX_GBI_2 -DDMA_ROM=0x01F7C680 -DDMA_RAM=0x80400000 -DDMA_SIZE=0x0005DB50 src/ldr/ldr.S -o obj/ldr/ldr.S.o
mkdir -p bin/ldr
mips64-g++ -T gl-n64.ld -nostartfiles -specs=nosys.specs -Wl,--gc-sections  -Wl,--defsym,start=0x80000400 obj/ldr/ldr.S.o  -o bin/ldr/ldr.elf
mips64-objcopy -S -O binary bin/ldr/ldr.elf bin/ldr/ldr.bin
inserting payload
Packing patch/wadextract into patch/gz-oot-1.2-j-vc.wad
Gathering WAD Header Information
Reading cert.cert
Reading ticket.cert
Reading metadata.tmd
Generating Footer signature
Generating content5.app u8 archive
Modifying content metadata in the TMD
Applying patch/gzi/gz_mem_patch.gzi gzi patches
Parsing gzi file patch/gzi/gz_mem_patch.gzi
Running gzi commands
Setting current file to 1
Apply patch to 1. offset 0x2eb0 = 0x60000000
Applying patch/gzi/hb_NACJ.gzi gzi patches
Parsing gzi file patch/gzi/hb_NACJ.gzi
Running gzi commands
Setting current file to 1
Apply patch to 1. offset 0x3d300 = 0x3c800040
Apply patch to 1. offset 0x85726 = 0x9010
Apply patch to 1. offset 0x8572c = 0x60000000
Apply patch to 1. offset 0x85738 = 0x60000000
Apply patch to 1. offset 0x2ea8 = 0x3c809000
Apply patch to 1. offset 0x2eac = 0x38840800
Apply patch to 1. offset 0x2eb0 = 0x7c8903a6
Apply patch to 1. offset 0x2eb4 = 0x80630018
Apply patch to 1. offset 0x2eb8 = 0x4e800421
Setting current file to 100
Apply patch to 100. offset 0x18b = 0x3d
Applying patch/gzi/gz_remap_default.gzi gzi patches
Parsing gzi file patch/gzi/gz_remap_default.gzi
Running gzi commands
Setting current file to 1
Apply patch to 1. offset 0x16baf0 = 0x800
Apply patch to 1. offset 0x16baf4 = 0x400
Apply patch to 1. offset 0x16baf8 = 0x200
Apply patch to 1. offset 0x16bafc = 0x100
Apply patch to 1. offset 0x16bb04 = 0x20
Injecting dol file
patch/dol/hb-NACJ/homeboy.bin: No such file or directory
couldn't inject dol patch.: No such file or directory`

I am running Ubuntu through Windows Subsystem for Linux. Any ideas why this would be happening?

**Comment by glankk** [comment]
This is a recent change that hasn't been documented in the build guide yet. For SD card support on VC, as well as some other features that have been missing from VC previously, you need to install [devkitPPC](https://wiibrew.org/wiki/DevkitPPC) and compile the homeboy binaries (source here https://github.com/krimtonz/homeboy), and place them in `patch/dol/hb-NACE` and `patch/dol/hb-NACJ` for English and Japanese versions respectively. If you don't care about SD card support, you can create a wad without the homeboy binaries by passing `--no-homeboy` to `patch-wad`.

**Comment by AmiableNebula** [comment]
Okay, thank you for the quick reply!
