### ISSUE TITLE
Suggestion: Safecheck

### ISSUE THREAD

**Issue by GB127** [glankk/gz#50]
Just a small suggestion :

I accidently made the command return from menu "L", and thus wasn't able to enter any menus as it exited out each time. I was forced to reset the game without saving anything.

I'd sugest to make sure you can't do "return from menu" with only "L".

**Comment by krimtonz** [comment]
There is a list of inputs you can give to load the default settings.

https://github.com/glankk/gz/blob/master/USAGE.md#210-settings

**Comment by GB127** [comment]
I just read this before seeing this miessage. This is absolutely on me.
