### ISSUE TITLE
Porting ROM Patch to 1.2

### ISSUE THREAD

**Issue by terry1994** [glankk/gz#6]
Hi,

I've looked into porting the rom patch over to the 1.2 ROM. From what I can tell there are two main things that need to be achieved:

* Copy the gz binary from a location in the ROM to a location in the RAM.
* Patch the ROM to use the text hook.

I am having trouble porting the code from 1.1. I can see that you're making changes to the bootloader, as you mentioned in another post. However, I am not overly familiar with MIPS. Do you have any pointers on how to go about this? I can make out potions of the modified bootloader but I am unfamiliar with various functions that it calls.

Also, not very relevant, but have you had any chance to review the pull request, I made the adjustments that you recommended making.

Thanks!

**Comment by glankk** [comment]
Hello Terry!

Sorry about the delay on your PR, I've been postponing it until the changes to the toolchain were ready. The next commit will include a new tool that will aid in automating the process of making patches. The process will be fully self-documented in code, and everything needed to make a patch will be included in the repository. There will also be full integration and support of your changes, including automatic patch creation. It should be ready soon. Meanwhile, your code looks good and will be merged.

Cheers!

**Comment by terry1994** [comment]
Awesome, I just saw your commit to the n64 took chain. I didn't realise how much work was involved but the tool you've created looks to be very thorough, great work.
