### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by terry-au** [glankk/gz#7]
What are your thoughts on some features such as enabling ISG and freezing countdown timers? I was also considering adding some predefined addresses to the memory watcher.

I was also thinking of adding the ability to disable gz at startup by holding a button combination.

**Comment by glankk** [comment]
These are all good suggestions. Features that continually interact with the game, such as endless ISG, would usually go in the "cheats" category. Predefined addresses have been discussed before, specifically Link's position/orientation and velocity have been requested. This would be a welcome feature.

**Comment by glankk** [comment]
These features have all been included in some form as of release 0.3.2. Closing.
